const PDFDocument = require('pdfkit');

const generatePDF = async (user, testResult) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument();
      const buffers = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(buffers);
        resolve(pdfBuffer);
      });

      // Header
      doc.fontSize(20).text('AKSHAR - Dyslexia Detection Report', { align: 'center' });
      doc.moveDown();
      
      // Date
      doc.fontSize(12).text(`Report Generated: ${new Date().toLocaleDateString()}`, { align: 'right' });
      doc.moveDown(2);
      
      // Parent Information
      doc.fontSize(16).text('Parent Information:', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(12);
      doc.text(`Parent Name: ${user.parentName}`);
      doc.text(`Email: ${user.email}`);
      doc.text(`Area: ${user.area}`);
      doc.text(`Child Age: ${user.childAge} years`);
      doc.moveDown(2);
      
      // Test Information
      doc.fontSize(16).text('Test Information:', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(12);
      doc.text(`Test Type: ${testResult.testType.charAt(0).toUpperCase() + testResult.testType.slice(1)} Test`);
      doc.text(`Test Date: ${testResult.createdAt.toLocaleDateString()}`);
      doc.moveDown(2);
      
      // Results
      doc.fontSize(16).text('Results:', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(12);
      
      const resultText = testResult.result.hasDyslexia 
        ? 'Indicators of dyslexia detected' 
        : 'No significant indicators of dyslexia detected';
      
      doc.text(`Result: ${resultText}`);
      if (testResult.result.confidence) {
        doc.text(`Confidence Level: ${testResult.result.confidence}%`);
      }
      doc.moveDown();
      
      // Reasoning
      doc.fontSize(14).text('Analysis:', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(12);
      doc.text(testResult.result.reasoning, { width: 500, align: 'justify' });
      doc.moveDown(2);
      
      // Advice
      doc.fontSize(14).text('Recommendations:', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(12);
      doc.text(testResult.result.advice, { width: 500, align: 'justify' });
      doc.moveDown(2);
      
      // Precautions
      doc.fontSize(14).text('Precautions:', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(12);
      doc.text('• This screening tool is not a diagnostic instrument.', { width: 500 });
      doc.text('• Results should be interpreted by qualified professionals.', { width: 500 });
      doc.text('• Early intervention is key to helping children with reading difficulties.', { width: 500 });
      doc.text('• Regular monitoring of reading progress is recommended.', { width: 500 });
      doc.moveDown(2);
      
      // Nearest Doctor
      if (testResult.nearestDoctor && testResult.nearestDoctor.name) {
        doc.fontSize(14).text('Nearest Healthcare Professional:', { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(12);
        doc.text(`Doctor: ${testResult.nearestDoctor.name}`);
        doc.text(`Address: ${testResult.nearestDoctor.address}`);
        doc.text(`Phone: ${testResult.nearestDoctor.phone}`);
        doc.moveDown(2);
      }
      
      // Footer
      doc.fontSize(10).text('This report is generated by AKSHAR AI-based Dyslexia Detection System.', 
        { align: 'center', width: 500 });
      doc.text('For support, please contact our team.', { align: 'center', width: 500 });
      
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = {
  generatePDF
};